services:
  # the central secrets manager
  vault:
    image: hashicorp/vault:latest
    container_name: ${VAULT_HOSTNAME}
    ports:
      - "${VAULT_PORT}:${VAULT_PORT}"
    environment:
      # starts vault in 'dev' mode
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: "http://0.0.0.0:${VAULT_PORT}"
    cap_add:
      # prevent memory from being swapped to disk
      - IPC_LOCK
  vault-setup:
    image: hashicorp/vault:latest
    container_name: vault-setup
    user: root # <- TODO: change this for Linux users...
    depends_on:
      - vault
    volumes:
      # mount the initialization script
      - ./setup_vault.sh:/setup_vault.sh
      # mount the directory to write the role_id/secret_id
      - ./secrets:/secrets
      - ./certs:/certs
    environment:
      VAULT_ADDR: "http://${VAULT_HOSTNAME}:${VAULT_PORT}"
      VAULT_HOSTNAME: "${VAULT_HOSTNAME}"
      VAULT_PORT: "${VAULT_PORT}"
      OVERWHELMING_MINOTAUR_HOSTNAME: "${OVERWHELMING_MINOTAUR_HOSTNAME}"
      SIEGE_LEVIATHAN_HOSTNAME: "${SIEGE_LEVIATHAN_HOSTNAME}"
      STOIC_SPHYNX_HOSTNAME: "${STOIC_SPHYNX_HOSTNAME}"
      EAGER_GRYPHON_HOSTNAME: "${EAGER_GRYPHON_HOSTNAME}"
    # run the script using shell
    command: ["sh", "/setup_vault.sh"]
  # sidecar for the vault agent serving overwhelming-minotaur 
  vault-agent-overwhelming-minotaur:
    image: hashicorp/vault:latest
    container_name: vault-agent-${OVERWHELMING_MINOTAUR_HOSTNAME}
    restart: unless-stopped
    environment:
      # point to central Vault service
      VAULT_ADDR: "http://${VAULT_HOSTNAME}:${VAULT_PORT}"
      # these variables populate the template in agent-config.hcl
      VAULT_ROLE: "${OVERWHELMING_MINOTAUR_HOSTNAME}-role"
      COMMON_NAME: "${OVERWHELMING_MINOTAUR_HOSTNAME}"
    volumes:
      # read-write: the agent writes the generated certs here
      - ./certs/${OVERWHELMING_MINOTAUR_HOSTNAME}:/app/certs
      # read-only: the agent reads the RoleID/SecretID created by setup_vault.sh
      - ./secrets/${OVERWHELMING_MINOTAUR_HOSTNAME}:/app/secrets
      # mount the configuration file
      - ./agent-config.hcl:/app/agent-config.hcl
    healthcheck:
      test: "test -f /app/certs/identity.pem"
      interval: 1s       # check every x seconds
      timeout: 5s        # wait x seconds for check to complete
      retries: 10          # unhealtht if x failures
      start_period: 5s   # grace period for the container to boot before checking
    command: ["vault", "agent", "-config=/app/agent-config.hcl"]
    depends_on:
      vault:
        condition: service_started
      vault-setup:
        condition: service_completed_successfully
  # sidecar for the vault agent serving siege-leviathan
  vault-agent-siege-leviathan:
    image: hashicorp/vault:latest
    container_name: vault-agent-${SIEGE_LEVIATHAN_HOSTNAME}
    restart: unless-stopped
    environment:
      # point to central Vault service
      VAULT_ADDR: "http://${VAULT_HOSTNAME}:${VAULT_PORT}"
      # these variables populate the template in agent-config.hcl
      VAULT_ROLE: "${SIEGE_LEVIATHAN_HOSTNAME}-role"
      COMMON_NAME: "${SIEGE_LEVIATHAN_HOSTNAME}"
    volumes:
      # read-write: the agent writes the generated certs here
      - ./certs/${SIEGE_LEVIATHAN_HOSTNAME}:/app/certs
      # read-only: the agent reads the RoleID/SecretID created by setup_vault.sh
      - ./secrets/${SIEGE_LEVIATHAN_HOSTNAME}:/app/secrets
      # mount the configuration file
      - ./agent-config.hcl:/app/agent-config.hcl
    healthcheck:
      test: "test -f /app/certs/identity.pem"
      interval: 1s       # check every x seconds
      timeout: 5s        # wait x seconds for check to complete
      retries: 10          # unhealthy if x failures
      start_period: 5s   # grace period for the container to boot before checking
    command: ["vault", "agent", "-config=/app/agent-config.hcl"]
    depends_on:
      vault:
        condition: service_started
      vault-setup:
        condition: service_completed_successfully
  # sidecar for the vault agent serving stoic-sphynx
  vault-agent-stoic-sphynx:
    image: hashicorp/vault:latest
    container_name: vault-agent-${STOIC_SPHYNX_HOSTNAME}
    restart: unless-stopped
    environment:
      # point to central Vault service
      VAULT_ADDR: "http://${VAULT_HOSTNAME}:${VAULT_PORT}"
      # these variables populate the template in agent-config.hcl
      VAULT_ROLE: "${STOIC_SPHYNX_HOSTNAME}-role"
      COMMON_NAME: "${STOIC_SPHYNX_HOSTNAME}"
    volumes:
      # read-write: the agent writes the generated certs here
      - ./certs/${STOIC_SPHYNX_HOSTNAME}:/app/certs
      # read-only: the agent reads the RoleID/SecretID created by setup_vault.sh
      - ./secrets/${STOIC_SPHYNX_HOSTNAME}:/app/secrets
      # mount the configuration file
      - ./agent-config.hcl:/app/agent-config.hcl
    healthcheck:
      test: "test -f /app/certs/identity.pem"
      interval: 1s       # check every x seconds
      timeout: 5s        # wait x seconds for check to complete
      retries: 10          # unhealtht if x failures
      start_period: 5s   # grace period for the container to boot before checking
    command: ["vault", "agent", "-config=/app/agent-config.hcl"]
    depends_on:
      vault:
        condition: service_started
      vault-setup:
        condition: service_completed_successfully
  # the overwhelming-minotaur service
  overwhelming-minotaur:
    build:
      context: ./overwhelming-minotaur
      dockerfile: Dockerfile
    container_name: ${OVERWHELMING_MINOTAUR_HOSTNAME}
    restart: on-failure
    ports:
      - "${OVERWHELMING_MINOTAUR_PORT}:${OVERWHELMING_MINOTAUR_PORT}"
    environment:
      PORT: ${OVERWHELMING_MINOTAUR_PORT}
      CERT_FILE: ${OVERWHELMING_MINOTAUR_CERT}
      KEY_FILE: ${OVERWHELMING_MINOTAUR_KEY}
    volumes:
      # mount the shared certs directory (target for agent, source for the app)
      - ./certs/${OVERWHELMING_MINOTAUR_HOSTNAME}:/app/certs:ro
    depends_on:
      vault-agent-overwhelming-minotaur:
        condition: service_healthy
  # the siege-leviathan service
  siege-leviathan:
    build:
      context: ./siege-leviathan
      dockerfile: Dockerfile
    container_name: ${SIEGE_LEVIATHAN_HOSTNAME}
    restart: on-failure
    ports:
      - "${SIEGE_LEVIATHAN_PORT}:${SIEGE_LEVIATHAN_PORT}"
    environment:
      TARGET_URL: https://${OVERWHELMING_MINOTAUR_HOSTNAME}:${OVERWHELMING_MINOTAUR_PORT}
      PORT: ${SIEGE_LEVIATHAN_PORT}
      CERT_BUNDLE: ${SIEGE_LEVIATHAN_CERT_BUNDLE}
    volumes:
      # mount the shared certs directory (target for agent, source for the app)
      - ./certs/${SIEGE_LEVIATHAN_HOSTNAME}:/app/certs:ro
    depends_on:
      vault-agent-siege-leviathan:
        condition: service_healthy
  # the reckless-sleuth service
  reckless-sleuth:
    build:
      context: ./reckless-sleuth
      dockerfile: Dockerfile
    container_name: ${RECKLESS_SLEUTH_HOSTNAME}
    restart: on-failure
    ports:
      - "${RECKLESS_SLEUTH_PORT}:${RECKLESS_SLEUTH_PORT}"
    environment:
      TARGET_URL: https://${OVERWHELMING_MINOTAUR_HOSTNAME}:${OVERWHELMING_MINOTAUR_PORT}
      PORT: ${RECKLESS_SLEUTH_PORT}

